destination:  ./_site

layouts_dir:  _layouts
includes_dir: _includes

baseurl: /docs

defaults:
  -
    values:
      layout: "docs"

include:     ['.htaccess']
exclude:
  - _config.yaml
  - example.info
  - Gemfile
  - Gemfile.lock
  - README.md

keep_files:  ['.git']

markdown:    kramdown

highlighter: rouge

permalink:   :title/

collections:
  - patterns
  - docs_quick-start
  - docs_using-snyk
  - docs_faqs
  - docs_ci
  - docs_github
  - docs_gitlab
  - docs_ignoring-issues
  - docs_orgs
  - docs_security
  - docs_badges
  - docs_landing
  - docs_bitbucket
  - docs_slack-integration
  - docs_broker
  - docs_java
  - docs_python
  - docs_scala
  - docs_ruby
  - docs_golang
  - docs_dotnet
  - docs_php
  - docs_nodejs
  - docs_heroku
  - docs_aws-lambda
  - docs_cloud-foundry
  - docs_pivotal-web-services
  - docs_bitbucket-server
  - docs_groups
  - docs_reports
  - docs_licenses
  - docs_notifications
